
# R implementation of 
# /*
# * This is a C implementation of the geodesic algorithms described in
# *
# *   C. F. F. Karney,
# *   Algorithms for geodesics,
# *   J. Geodesy <b>87</b>, 43--55 (2013);
# *   https://dx.doi.org/10.1007/s00190-012-0578-z
# *   Addenda: http://geographiclib.sf.net/geod-addenda.html
# *
# * See the comments in geodesic.h for documentation.
# *
# * Copyright (c) Charles Karney (2012-2014) <charles@karney.com> and licensed
# * under the MIT/X11 License.  For more information, see
# * http://geographiclib.sourceforge.net/
# */

# 
# Robert Hijmans
# May 2015
# version 1
# license GPL3


# Solve the direct geodesic problem.
geodesic <- function(p, azi, d, a=6378137, f=1/298.257223563, ...) { 
  p <- .pointsToMatrix(p)
  p <- cbind(p[,1], p[,2], azi, d)
  r <- .geodesic(as.double(p[,1]), as.double(p[,2]), as.double(p[,3]), as.double(p[,4]), as.double(a), as.double(f))
  r <- matrix(r, ncol=3, byrow=TRUE)
  colnames(r) <- c('longitude', 'latitude', 'azimuth')
  r
}

# Solve the inverse geodesic problem.
geodesic_inverse <- function(p1, p2, a=6378137, f=1/298.257223563, ...) { 
  p1 <- .pointsToMatrix(p1)
  p2 <- .pointsToMatrix(p2)
  p <- cbind(p1[,1], p1[,2], p2[,1], p2[,2])
  r <- .inversegeodesic(as.double(p[,1]), as.double(p[,2]), as.double(p[,3]), as.double(p[,4]), as.double(a), as.double(f))
  r <- matrix(r, ncol=3, byrow=TRUE)
  colnames(r) <- c('distance', 'azimuth1', 'azimuth2')
  r
}

# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.geodesic <- function(lon1, lat1, azi1, s12, a, f) {
  .Call(`_geosphere_geodesic`, lon1, lat1, azi1, s12, a, f)
}

.inversegeodesic <- function(lon1, lat1, lon2, lat2, a, f) {
  .Call(`_geosphere_inversegeodesic`, lon1, lat1, lon2, lat2, a, f)
}

.polygonarea <- function(lon, lat, a, f) {
  .Call(`_geosphere_polygonarea`, lon, lat, a, f)
}

.geod_intermediate <- function(lon1, lat1, lon2, lat2, n, distance, arc, a, f) {
  .Call(`_geosphere_geodesic_nodes`, lon1, lat1, lon2, lat2, n, distance, arc, a, f)
}

.OSGB <- function(x, y, p, geo) {
  .Call(`_geosphere_osgb`, x, y, p, geo)
}

.OSGBinv <- function(g, prec, centerp) {
  .Call(`_geosphere_osgb_rev`, g, prec, centerp)
}

.pointsToMatrix <- function(p, checkLonLat=TRUE, poly=FALSE) {
  if (inherits(p, 'SpatVector')) {
    stopifnot(terra::geomtype(p) == "points")
    test <- terra::is.lonlat(p)
    if (! isTRUE (test) ) {
      if (is.na(test)) {
        warning('Coordinate reference system of SpatVector is not set. Assuming it is degrees (longitude/latitude)!')  			
      } else if (checkLonLat) {
        p <- terra::project(p, "+proj=longlat")
      }
    }
    p <- terra::crds(p)
  } else if (inherits(p, 'SpatialPoints')) {
    test <- !sp::is.projected(p)
    if (! isTRUE (test) ) {
      if (is.na(test)) {
        warning('Coordinate reference system of SpatialPoints object is not set. Assuming it is degrees (longitude/latitude)!')  			
      } else if (checkLonLat) {
        stop('Points are projected. They should be in degrees (longitude/latitude)')  
      }
    }
    p <- sp::coordinates(p)
  } else if (is.data.frame(p)) {
    p <- as.matrix(p)
  } else if (is.vector(p)){
    if (length(p) != 2) {
      stop('Wrong length for a vector, should be 2')
    } else {
      p <- matrix(p, ncol=2) 
    }
  } else if (is.matrix(p)) {
    if (ncol(p) != 2) {
      stop( 'A points matrix should have 2 columns')
    }
    cn <- colnames(p)
    if (length(cn) == 2) {
      if (toupper(cn[1]) == 'Y' | toupper(cn[2]) == 'X')  {
        warning('Suspect column names (x and y reversed?)')
      }
      if (toupper(substr(cn[1],1,3) == 'LAT' | toupper(substr(cn[2],1,3)) == 'LON'))  {
        warning('Suspect column names (longitude and latitude reversed?)')
      }
    }		
  } else {
    stop('points should be vectors of length 2, matrices with 2 columns, or inheriting from a SpatialPoints or SpatVector object')
  }
  
  if (! is.numeric(p) ) { p[] <- as.numeric(p) }
  
  if (checkLonLat & nrow(p) > 0) {
    if (length(stats::na.omit(p[,1])) > 0) {
      if (min(p[,1], na.rm=TRUE) < -360) { stop('longitude < -360') }
      if (max(p[,1], na.rm=TRUE) > 360) {  stop('longitude > 360')  }
      if (min(p[,1], na.rm=TRUE) < -180) { warning('longitude < -180') }
      if (max(p[,1], na.rm=TRUE) > 180) {  warning('longitude > 180')  }
    }
    if (length(stats::na.omit(p[,2])) > 0) {
      if (min(p[,2], na.rm=TRUE) < -90) {  stop('latitude < -90')  }
      if (max(p[,2], na.rm=TRUE) > 90) {  stop('latitude > 90')  }
    }
  }
  
  
  if (poly) {
    if (! isTRUE(all.equal(p[1,], p[nrow(p),]))) {
      p <- rbind(p, p[1,])
    } 
    
    i <- p[-nrow(p),1] == p[-1,1] &  p[-nrow(p),2] == p[-1,2]
    i <- which(isTRUE(i))
    if (length(i) > 0) {
      p <- p[-i, ,drop=FALSE]
    }
    
    .isPolygon(p)
  }
  
  return(p)
}

distGeo <- function(p1, p2, a=6378137, f=1/298.257223563) {
  p1 <- .pointsToMatrix(p1) 
  if (missing(p2)) {
    if (nrow(p1) == 1) return(0)
    if (nrow(p1) == 0) return(NULL)
    p2 <- p1[-1, ,drop=FALSE]
    p1 <- p1[-nrow(p1), ,drop=FALSE]
    addNA <- TRUE
  } else {
    p2 <- .pointsToMatrix(p2)
    addNA <- FALSE
  }
  p  <- cbind(p1[,1], p1[,2], p2[,1], p2[,2])
  r <- .inversegeodesic(as.double(p[,1]), as.double(p[,2]), as.double(p[,3]), as.double(p[,4]), as.double(a), as.double(f))
  r <- matrix(r, ncol=3, byrow=TRUE)
  if (addNA){
    c(r[,1], NA) 
  } else {
    r[,1]
  }
}


.distm1 <- function(x, fun) {
  n = nrow(x)
  dm = matrix(0, ncol=n, nrow=n)
  if (n == 1) {	
    return(dm) 	
  }
  for (i in 2:n) {
    j = 1:(i-1)
    dm[i,j] = fun(x[i,], x[j,])
  }
  
  dm <- dm+t(dm)
  return(dm)
}


distm <- function(x, y, fun=distGeo) {
  x <- .pointsToMatrix(x)
  
  if (missing(y)) {
    return( .distm1(x, fun) )
  }
  
  y <- .pointsToMatrix(y)
  n = nrow(x)
  m = nrow(y)
  
  dm = matrix(ncol=m, nrow=n)
  for (i in 1:n) {
    dm[i,] = fun(x[i,], y)
  }
  return(dm)
}